import { Building2, Music, Clock, Home, Theater, Church, LucideIcon } from "lucide-react";

export type CategoryKey =
    | "Projekti"
    | "Ostali projekti"
    | "Oprema za club-ove"
    | "HOTELI"
    | "KAZALIŠTA"
    | "SAKRALNI OBJEKTI";

export const referencesData: Record<CategoryKey, string[]> = {
    Projekti: [
        "HRT - Zagreb - digitalni središnji sustav komunikacije - RIEDEL",
        "Informativni centar RADIO POSTAJA MIR - MEĐUGORJE",
        "Hotel LONE - Rovinj - AV & MULTIMEDIJALNI SUSTAV",
        "ADRIS GRUPA - POSLOVNA ZGRADA - Zagreb - AV & MULTIMEDIJALNI SUSTAV",
        "POVIJESNI MUZEJ - Zagreb - AV & MULTIMEDIJALNI SUSTAV",
        "Hotel EXCELSIOR - Lovran - AV & MULTIMEDIJALNI SUSTAV",
        "SPALADIUM ARENA - Split - audio, video, multimedija, rezultatski semafori",
        "DVORANA ŽATIKA - audio, video, multimedija",
        "Medicinski fakultet Split",
        "Klinika za ginekologiju KBC Split",
        "Kuća slave splitskog sporta - Split",
        "Ulica Olimpijaca - Split",
        "Očna klinika KBC - Split",
        "GALERIJA UMJETNINA - Split",
        "Odjel kirurgije bolnice Zadar",
        "RADIO POSTAJA MIR - Međugorje",
        "CARINSKI PAVILJON - Zadar (LED display-i)",
        "Muzej antičkog stakla - Zadar (multimedijalni sustav)",
        "Arheološki muzej - Zadar",
        "Multimedijalni centar Split",
        "Glazbena škola Josip Hatze",
        "Trajektni terminal GAŽENICA - Zadar, AV & Multimedijalni sustav",
        "Hotel LONE - ROVINJ, AV & Multimedijalni sustav",
        "Hotel MARJAN HILTON - Split, AV & Multimedijalni sustav",
    ],
    "Ostali projekti": [
        "Tonski studio \"BOBO\" Vrbnik, Ot.Krk",
        "Tonski studio TM - Split",
        "Video studio \"URBAN JUNGLE\" Split",
        "Televizija ATV Split",
        "Televizija KANAL 5 Split",
        "Radio postaja KL EURODOM Split",
        "Radio postaja SVID - Rijeka",
        "Radio postaja OK - otok Krk",
        "Radio Jaska - Jastrebarsko",
        "Federalna TV - Sarajevo, tonski dio",
        "Trgovački centri JOLLY - Šibenik",
        "Robna kuća RAVEL - Split",
        "Auto kuća CITROEN - Split",
        "Robna kuća JOLLY - Šibenik",
    ],
    "Oprema za club-ove": [
        // SPLITSKA REGIJA
        "Disco club \"SHAKESPEARE\" Split",
        "Disco club \"PALLADIUM\" Split",
        "Disco club \"PAGANINI\" Split",
        "Disco club \"UP and DOWN\" Split",
        "Disco club \"A 90\" Split",
        "Disco club \"FENIX\" Supetar",
        "Disco club \"BRETANIDE\" Bol",
        "Disco club \"FANATIC\" Bol",
        "Disco club \"MIRAKUL\" Humac",
        "Disco club \"CASANOVA\" Trogir",
        "Disco club \"MONTE CARLO\" Pučišća",
        "Disco club \"F 1\" Trogir",
        "Disco club \"MASTER'S CLUB\" Split",
        "Disco club \"FACES CLUB\" Bol",
        "Disco club \"NEČUJAM\" ot. Šolta",
        "Disco club \"MLIN\" Jelsa ot. Hvar",
        "Caffe club \"STAR ROCK CAFFE\" Split",
        "Caffe club \"ALL STAR\" Split",
        "Caffe club \"EMANUEL\" Split",
        "Caffe club \"PINO\" Split",
        "Caffe club \"BAČVICE\" Split",
        "Caffe club \"ŠKARPELIN\" Split",
        "Caffe club \"FIBRA\" Split",
        "Disco club \"HACIENDA\" ot. Brač",
        "Pivnica \"ZLATNI ROG\" Split",
        "Disco club \"DISCOVERY\" Split",

        // DUBROVAČKA REGIJA
        "Disco club \"SUN CITY\" Dubrovnik",
        "Disco club \"ALCATRAZ\" Dubrovnik",
        "Disco club \"MOZART\" Metković",
        "Caffe - disco club \"ODISEJ\" Orebić",
        "Disco club \"MOBY DICK\" Orebić",
        "Cabare club \"LABIRINT\" Dubrovnik",

        // MAKARSKA REGIJA
        "Disco club \"OPERA\" Makarska",
        "Disco club \"GAUDEAMUS\" Makarska",
        "Disco club \"JAGUAR\" Imotski",
        "Night club \"PJER\" Makarska",
        "Caffe \"CASABLANCA\" Makarska",
        "Disco club \"PETAR PAN\" Makarska",

        // ŠIBENSKA REGIJA
        "Disco club \"AURORA\" Primošten",
        "Disco club \"MIDNIGHT\" Zablaće",
        "Disco club \"KINO\" Tisno",
        "Disco club \"KAPELA\" Vodice",
        "Disco club \"CLUB 58\" Drniš",

        // ZADARSKA REGIJA
        "Disco club \"SATURNUS\" Zadar",
        "Disco club \"COCOS\" Kukljica, Ot. Ugljan",

        // HRVATSKA I INOZEMSTVO
        "Disco club \"AQUARIUS\" Medulin, Pula",
        "Disco club \"PLAVA STRIJELA\" Samobor",
        "Disco club \"VEGA\" Osijek",
        "Disco club \"LEE\" Samobor",
        "Club \"SVID ROCK CAFFE\" Rijeka",
        "Disco club \"MONACO\" Nova Bila",
        "Disco club \"METAMORFOZA\" Vitez",
        "Disco club \"MIAMI\" Kiseljak",
        "Disco club \"BASTION\" Posušje",
        "Disco club \"ALAN FORD\" CZ Republika",
        "Disco club \"SEVASTOPOL\" Ukraine",
        "Disco club \"ROYAL\" Uskoplje",
        "Disco club \"MONACO\" Zavidovići",
        "Disco club \"LEPTIR\" Busovača",
        "Disco club \"LIVNO\" Livno, hotel \"Park\"",
        "Disco club \"PALADIUM\" Mostar",
    ],
    HOTELI: [
        "Kongresne dvorane hotel \"ART\" Split",
        "Kongresna dvorana hotel \"OMORIKA\" - Crikvenica",
        "Kongresna dvorana hotel \"SNJEŽNIK\" - Gerovo",
        "Hotel SOLARIS - Šibenik",
        "Ozvučenje hotela i kongresna dvorana \"BONADEA\" Duce",
        "Ozvučenje hotel \"STUDENAC\" Omiš",
        "Ozvučenje recepcije i restorana hotela \"BORAK\" - Bol",
        "Kongresni centar, night club i casino \"Le Meridien Hotel LAV\" - Podstrana",
        "Kongresna dvorana hotela \"ZORA\" - Primošten",
        "Video sustav kongresnih dvorana hotel \"AMFORA\" - Hvar",
        "Hotel OLYMPIA - Vodice, AV & Multimedijalni sustav",
        "Hotel PUNTA - Vodice, AV & Multimedijalni sustav",
        "Diskoteka SATURNUS - TN Zaton",
        "Hotel MARJAN - Split, AV & Multimedijalni sustav",
        "Hotel KORALJ - Umag - AV & Multimedijalni sustav",
        "Hotel AMFORA - Hvar - video sustav",
        "Hotel KOLOVARE - Zadar - AV & Multimedijalni sustav",
        "Hotel MONTE MULINI - Rovinj - AV & Multimedijalni sustav",
        "TN BELVEDERE - Vrsar - AV & Multimedijalni sustav",
        "TN PETALON - AV & Multimedijalni sustav",
    ],
    KAZALIŠTA: [
        "Hrvatsko narodno kazalište - Split",
        "Gradsko kazalište lutaka - Split",
        "Hrvatska kazališna kuća - Zadar",
        "Kazalište lutaka - Zadar",
        "Digitalni inspicijentski žični / bežični sustav komunikacije HNK Split",
        "Sustav unutrašnjeg i vanjskog ozvučenja HNK Split",
    ],
    "SAKRALNI OBJEKTI": [
        "Katedrala Sv. Dujma - Split",
        "Nadbiskupijsko sjemenište - Split, glavna dvorana",
        "Katedrala Sv. Lovre - Trogir",
        "Crkva Sv. Nikole - Trogir",
        "Katedrala - otok Krk",
        "Inauguracijska dvorana Ivana Pavla II, Nadbiskupijska palača - Split",
        "Samostan Milosrdne sestre Sv.Križa - Đakovo",
        "Crkva Sv. Dominika - Split",
        "Crkva Sv. Dimitrija - Beograd",
        "Konferencijska dvorana Nadbiskupijskog sjemeništa - Split",
        "Crkva Bezgrešnog začeća - K. Štafilić",
        "Pastoralni centar Sv. Ante, Šubićevac - Šibenik",
        "Nadbiskupsko bogoslovno sjemenište KAPTOL - Zagreb",
    ],
};

export const categoryIcons: Record<CategoryKey, LucideIcon> = {
    Projekti: Building2,
    "Ostali projekti": Clock,
    "Oprema za club-ove": Music,
    HOTELI: Home,
    KAZALIŠTA: Theater,
    "SAKRALNI OBJEKTI": Church,
};